server:
  type: simple
  applicationContextPath: /api
  adminContextPath: /admin
  connector:
    type: http
    port: 8084

logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: /log/session.log
      archive: false

databaseName: "h2"

database:
  driverClass: org.h2.Driver
  user: sa
#  password:
  url: jdbc:h2:./sessiondb
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
